blank_issues_enabled: false
contact_links:
  - name: To create a issue join the Amethyst Network discord
    url: https://discord.gg/J3VPy5Vy8x
  - name: Heroku, Repl.it, Blocked site issues
    url: https://www.youtube.com/embed/BLUkgRAy_Vo?mute=1&autoplay=1
    about: Do not create issues for these.